### ISSUE TITLE
Add links to framework home pages

### ISSUE THREAD

**Issue by GHNewbiee** [bunsvr/benchmark#5]
As per title.

**Comment by aquapi** [comment]
I will add another option in package json of every framework

**Comment by GHNewbiee** [comment]
I mean links in the table for each framework.

**Comment by aquapi** [comment]
Yes they will be in the readme after benchmarking

**Comment by aquapi** [comment]
I will create another script to display the description of each frameworks

**Comment by aquapi** [comment]
@GHNewbiee I added
