### ISSUE TITLE
Stric status(404) is returning 200

### ISSUE THREAD

**Issue by gjovanov** [bunsvr/benchmark#6]
I was just trying to run all benchmarks and it seems that the validation test for `stric` `404` is failing.

It displays `404` as a text but its status is `200`.

![image](https://github.com/bunsvr/benchmark/assets/2255435/1d5bfb9f-ee78-4d1a-acd6-99b58e270321)

**Comment by aquapi** [comment]
@gjovanov I'm making a new benchmark but not for Stric
this benchmark can work with every runtime (Deno, Node, Python or anything)
Should finish this in 2 days
Also I dropped Stric
You should take a look of what I'm doing here: https://github.com/bit-js/byte
